"""
Frozen acceptance thresholds from the project report (Phase 5).

Used by Phases 6–8 for validation gates and deployment decisions.
"""

# §4.1 NLP workload classification
NLP_MIN_WORD_COUNT_FOR_TRAINING = 10
NLP_AUTO_ASSIGN_CONFIDENCE = 0.85  # 85%+ → direct assignment without manual review
NLP_CONFIDENCE_BOOST_MIN = -0.2
NLP_CONFIDENCE_BOOST_MAX = 0.2

# §4.2 Ensemble storage tier prediction (report targets)
ENSEMBLE_WEIGHT_RULE = 0.30
ENSEMBLE_WEIGHT_RANDOM_FOREST = 0.35
ENSEMBLE_WEIGHT_XGBOOST = 0.35
ENSEMBLE_TARGET_ACCURACY = 0.893
ENSEMBLE_HIGH_CONFIDENCE_THRESHOLD = 0.85
ENSEMBLE_LOW_CONFIDENCE_THRESHOLD = 0.50

RULE_EXPERT_STANDALONE_ACCURACY_TARGET = 0.76
RF_STANDALONE_ACCURACY_TARGET = 0.841
XGB_STANDALONE_ACCURACY_TARGET = 0.867

# §4.3 Lifecycle (reference — implemented in tiering_tasks)
LIFECYCLE_HOT_TO_WARM_DAYS = 30
LIFECYCLE_WARM_TO_COLD_DAYS = 90
LIFECYCLE_PROMOTION_ACCESS_WINDOW_DAYS = 5
LIFECYCLE_PROMOTION_MIN_ACCESSES = 2

# §4.5 Feedback-driven retraining
FEEDBACK_MIN_SCORE_FOR_TRAINING = 0.5
FEEDBACK_EVALUATION_WINDOW_DAYS_MIN = 7
FEEDBACK_EVALUATION_WINDOW_DAYS_MAX = 30
RETRAIN_MIN_ABSOLUTE_GAIN = 0.01  # 1% accuracy improvement
RETRAIN_MIN_RELATIVE_GAIN = 0.02  # 2% relative improvement
